name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Gather CI configuration
        id: matrix
        uses: laminas/laminas-ci-matrix-action@1.24.0

  qa:
    name: QA Checks
    needs: [matrix]
    runs-on: ${{ matrix.operatingSystem }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - name: ${{ matrix.name }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          AKISMET_KEY: ${{ secrets.AKISMET_KEY }}
          AKISMET_BLOG: ${{ secrets.AKISMET_BLOG }}
        uses: laminas/laminas-continuous-integration-action@1.35.1
        with:
          job: ${{ matrix.job }}
