name: Scheduled Test Suite
on:
  schedule:
    - cron: '30 10 * * 1'
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Scheduled Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.25.0
        with:
          php-version: 8.1
      - name: Install latest dependencies
        run: composer update --prefer-dist --no-progress
      - name: PHPUnit
        run: vendor/bin/phpunit
        env:
          AKISMET_KEY: ${{ secrets.AKISMET_KEY }}
          AKISMET_BLOG: ${{ secrets.AKISMET_BLOG }}
